name: Enable Dependabot Auto-Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    uses: Staffbase/gha-workflows/.github/workflows/template_automerge_dependabot.yml@create-depdendabot-automerge
