name: release-git

on:
  release:
    types: [published]

jobs:
  bump-version-and-release:

    runs-on: ubuntu-latest

    steps:
      - name: bump readme version
        uses: undergroundwires/bump-everywhere@1.4.0
