name: Release Version Detector

on:
  push:
    branches:
      - main

jobs:
  new_version:
    uses: Staffbase/gha-workflows/.github/workflows/template_release_version.yml@add-format-release-version

  echo:
    runs-on: ubuntu-latest
    needs: new_version
    steps:
      - run: echo ${{ needs.new_version.outputs.new_version }}
      - run: echo ${{ needs.new_version.outputs.new_tag }}
