name: Label Orchestrator

on:
  pull_request:
    types: [labeled]

jobs:
  web-ui-tests:
    if: github.event.label.name == 'dev'
    uses: ./.github/workflows/workflow1.yml
    secrets: inherit

  native-ui-tests:
    if: github.event.label.name == 'invalid'
    uses: ./.github/workflows/workflow2.yml
    secrets: inherit
