name: Label Orchestrator

on:
  pull_request:
    types: [labeled]

jobs:
  web-ui-tests:
    if: contains(github.event.pull_request.labels.*.name, 'dev')
    uses: ./.github/workflows/workflow1.yml
    secrets: inherit

  native-ui-tests:
    if: contains(github.event.pull_request.labels.*.name, 'invalid')
    uses: ./.github/workflows/workflow2.yml
    secrets: inherit
