name: Print Variables

on:
  release:
    types: [published]
  push:
    branches:
      - '**'
  pull_request:
    types: [labeled, unlabeled, opened, closed]
  workflow_call:
  workflow_run:
    workflows: ["Autodev"]
    types:
      - completed

jobs:
  print:
    name: Printing
    runs-on: ubuntu-latest

    outputs:
      test: "Hello World"

    steps:
      - run: echo '${{ toJSON(github) }}'

  output:
    name: Output
    needs: print
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_OUTPUT
      - run: echo ${{ needs.print.result }}
