name: Print Variables

on:
  push:
    tags:
      - '*'
    branches:
      - '**'
  pull_request:
    types: [labeled, unlabeled]

jobs:
  print:
    name: Printing
    runs-on: ubuntu-latest

    steps:
      - run: echo '${{ toJSON(github) }}'
