name: Print Variables

on:
  release:
    types: [published]
  push:
    branches:
      - '**'
  pull_request:
    types: [labeled, unlabeled, opened, closed]

jobs:
  print:
    name: Printing
    runs-on: ubuntu-latest

    outputs:
      test: "Hello World"

    steps:
      - run: exit 1

  output:
    name: Output
    needs: print
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_OUTPUT
      - run: echo ${{ needs.print.result }}
      - run: echo ${{ needs.print.outputs.test }}
