name: Test

on:
  workflow_call:
    inputs:
      test1:
        required: false
        default: |-
          test1_content1
        type: string
      test2:
        required: false
        default: |-
          test3_content1${{ github.name }}further_content
        type: string

jobs:
  test:

    name: Test
    runs-on: ubuntu-20.04

    steps:
      - run: echo ${{ inputs.test1 }}
      - run: echo ${{ inputs.test2 }}
