name: Test

on:
  workflow_call:
    inputs:
      force:
        default: 'false'
        required: false
        type: boolean

jobs:
  test:

    name: test
    runs-on: ubuntu-22.04

    steps:

      - name: test
        run: |
          if [ ${{ inputs.force }} == 'true' ]; then
            echo "if case"
          else
            echo "else case"
          fi
